import React, { useState, useMemo } from 'react';
import { Flame, Sparkles, Info, ShieldAlert, RefreshCw, Activity, HeartHandshake } from 'lucide-react';
import { calculateAbjadValue } from '../../utils/abjad';
import { ExportFormatButtons } from '../common/ExportFormatButtons';

interface MizanHararahTabProps {
  language: string;
}

// Letter Fire Intensity classification
const FIRE_LETTERS = new Set(['ا', 'أ', 'إ', 'آ', 'ه', 'ط', 'م', 'ف', 'ش', 'ذ']);

export default function MizanHararahTab({ language }: MizanHararahTabProps) {
  const [inputText, setInputText] = useState<string>('يا قهار يا جبار يا عزيز');
  const [repetitions, setRepetitions] = useState<number>(1000);

  const analysis = useMemo(() => {
    let fireCount = 0;
    let totalLetters = 0;

    for (const char of inputText) {
      if (/[\u0600-\u06FF]/.test(char)) {
        totalLetters++;
        if (FIRE_LETTERS.has(char)) {
          fireCount++;
        }
      }
    }

    const fireRatio = totalLetters > 0 ? fireCount / totalLetters : 0.4;
    const baseAbjad = calculateAbjadValue(inputText) || 300;

    // Thermal Load Calculation
    const totalThermalUnits = Math.round(baseAbjad * fireRatio * (repetitions / 100));
    // Mental Fatigue Risk (0 - 100%)
    const fatigueRiskPct = Math.min(100, Math.round((totalThermalUnits / 5000) * 100));

    let riskLevelFr = 'Faible (Énergie Douce)';
    let riskLevelEn = 'Low (Gentle Energy)';
    let riskLevelHa = 'Kadan (Lafiya da Nutsuwa)';
    let riskColor = '#10b981';

    if (fatigueRiskPct > 70) {
      riskLevelFr = 'Élevé (Surchauffe Spirituelle & Fatigue Mentale)';
      riskLevelEn = 'High (Spiritual Overheating & Mental Fatigue)';
      riskLevelHa = 'Mai Yawa (Hatsarin Zafin Kai da Gajiya)';
      riskColor = '#ef4444';
    } else if (fatigueRiskPct > 40) {
      riskLevelFr = 'Modéré (Vigilance Recommandée)';
      riskLevelEn = 'Moderate (Vigilance Recommended)';
      riskLevelHa = 'Matsakaici (A Kula da Hankali)';
      riskColor = '#f59e0b';
    }

    // Cooling Counter-Balance Recommendations
    const coolingDhikrFr = 'Ya Salam (يا سلام) & Ya Halim (يا حليم)';
    const coolingDhikrEn = 'Ya Salam (Oh Peace) & Ya Halim (Oh Forbearing)';
    const coolingDhikrHa = 'Ya Salam da Ya Halim';

    const coolingFumigationFr = 'Santal Blanc, Camphre & Eau de Rose';
    const coolingFumigationEn = 'White Sandalwood, Camphor & Rose Water';
    const coolingFumigationHa = 'Sandal Fari, Camphre da Ruwan Huda';

    return {
      fireCount,
      totalLetters,
      fireRatioPct: Math.round(fireRatio * 100),
      baseAbjad,
      totalThermalUnits,
      fatigueRiskPct,
      riskLevelFr,
      riskLevelEn,
      riskLevelHa,
      riskColor,
      coolingDhikrFr,
      coolingDhikrEn,
      coolingDhikrHa,
      coolingFumigationFr,
      coolingFumigationEn,
      coolingFumigationHa,
    };
  }, [inputText, repetitions]);

  const handleDownloadSVG = () => {
    const svgElement = document.getElementById('mizan-hararah-svg');
    if (!svgElement) return;
    const svgData = new XMLSerializer().serializeToString(svgElement);
    const blob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `mizan_hararah_${inputText}.svg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="bg-white dark:bg-gray-900 rounded-3xl p-6 sm:p-8 shadow-xl border border-orange-500/30 space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3 border-b border-gray-100 dark:border-gray-800 pb-4">
        <div className="p-3 bg-orange-100 dark:bg-orange-900/50 rounded-2xl text-orange-600 dark:text-orange-400">
          <Flame size={24} />
        </div>
        <div>
          <h2 className="text-lg font-bold text-gray-900 dark:text-white">
            {language === 'en'
              ? 'Mizan al-Hararah (Thermal & Mental Fatigue Gauge)'
              : language === 'ha'
              ? 'Mizan al-Hararah (Gwajin Zafin Wuta da Gajiya)'
              : 'Mizan al-Hararah (Jauge de Chaleur Spirituelle & Prévention Fatigue Mentale)'}
          </h2>
          <p className="text-xs text-gray-500 dark:text-gray-400">
            {language === 'en'
              ? 'Evaluates the Fire element ratio and spiritual thermal load generated by a litany to prevent mental exhaustion.'
              : language === 'ha'
              ? 'Auna yawan wuta da zafi na ambato domin kariya daga gajiya da zafin kai.'
              : 'Évalue la quantité d\'élément Feu générée par une litanie pour prévenir la fatigue mentale et la surchauffe spirituelle.'}
          </p>
        </div>
      </div>

      {/* Input Controls */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
        <div>
          <label className="block font-bold text-gray-700 dark:text-gray-300 mb-1">
            {language === 'en' ? 'Litany / Divine Name to Test:' : language === 'ha' ? 'Kalmar Ambato (Larabci):' : 'Litanie ou Noms Divins à Évaluer :'}
          </label>
          <input
            type="text"
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            placeholder="ex: يا قهار يا جبار..."
            className="w-full px-4 py-2.5 rounded-xl bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white font-bold text-base focus:ring-2 focus:ring-orange-500 outline-none"
          />
        </div>

        <div>
          <label className="block font-bold text-gray-700 dark:text-gray-300 mb-1">
            {language === 'en' ? 'Number of Repetitions (Count):' : language === 'ha' ? 'Adadin Karatun Ambato:' : 'Nombre de Répétitions Souhaité :'}
          </label>
          <input
            type="number"
            value={repetitions}
            onChange={(e) => setRepetitions(Math.max(1, Number(e.target.value)))}
            className="w-full px-4 py-2.5 rounded-xl bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white font-bold text-base focus:ring-2 focus:ring-orange-500 outline-none"
          />
        </div>
      </div>

      {/* Main Thermal Gauge SVG & Analysis */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Thermal SVG Dial (5 cols) */}
        <div className="lg:col-span-5 flex flex-col items-center justify-center p-6 bg-gradient-to-br from-orange-950 via-slate-950 to-red-950 rounded-3xl border border-orange-500/40 shadow-2xl text-center space-y-4">
          <div className="text-xs font-bold text-orange-300 uppercase tracking-widest flex items-center gap-1.5">
            <Sparkles size={14} />
            <span>{language === 'en' ? 'Spiritual Thermal Meter' : 'Indicateur de Chaleur Spirituelle'}</span>
          </div>

          <svg id="mizan-hararah-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 280" className="w-full max-w-[280px] h-auto drop-shadow-2xl">
            <rect width="320" height="280" fill="#0f172a" rx="20" />
            {/* Meter Arc background */}
            <path d="M 40 220 A 120 120 0 0 1 280 220" fill="none" stroke="#334155" strokeWidth="18" strokeLinecap="round" />

            {/* Colored Arc Gradient */}
            <path
              d="M 40 220 A 120 120 0 0 1 280 220"
              fill="none"
              stroke="url(#thermalGradient)"
              strokeWidth="18"
              strokeLinecap="round"
              strokeDasharray="376"
              strokeDashoffset={376 - (376 * analysis.fatigueRiskPct) / 100}
            />

            <defs>
              <linearGradient id="thermalGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" stopColor="#10b981" />
                <stop offset="50%" stopColor="#f59e0b" />
                <stop offset="100%" stopColor="#ef4444" />
              </linearGradient>
            </defs>

            {/* Needle Pivot */}
            <circle cx="160" cy="220" r="12" fill="#0f172a" stroke="#f97316" strokeWidth="3" />

            {/* Needle Line */}
            {(() => {
              const angleDeg = -180 + (analysis.fatigueRiskPct * 180) / 100;
              const rad = (angleDeg * Math.PI) / 180;
              const nx = 160 + 90 * Math.cos(rad);
              const ny = 220 + 90 * Math.sin(rad);
              return <line x1="160" y1="220" x2={nx} y2={ny} stroke="#ffffff" strokeWidth="4" strokeLinecap="round" />;
            })()}

            {/* Text Overlay */}
            <text x="160" y="170" textAnchor="middle" fill="#ffedd5" fontSize="28" fontFamily="monospace" fontWeight="bold">
              {analysis.fatigueRiskPct}%
            </text>
            <text x="160" y="195" textAnchor="middle" fill="#fdba74" fontSize="12" fontFamily="sans-serif">
              {language === 'en' ? 'Fatigue Index' : 'Indice de Risque de Fatigue'}
            </text>
          </svg>

          <div className="text-xs text-orange-200 font-mono">
            {language === 'en' ? 'Thermal Load:' : 'Charge Thermique :'} <span className="font-bold text-amber-300">{analysis.totalThermalUnits} U.T.</span>
          </div>

          <ExportFormatButtons
            svgId="mizan-hararah-svg"
            filename={`mizan_hararah_${inputText}`}
            title={language === 'en' ? 'Mizan al-Hararah Thermal Gauge' : 'Mizan al-Hararah Cadran Thermique'}
            subtitle={`Formule: ${inputText} • Risque: ${analysis.fatigueRiskPct}%`}
            language={language}
          />
        </div>

        {/* Diagnostic Metrics & Counter-Balance Protocol (7 cols) */}
        <div className="lg:col-span-7 space-y-4">
          <div className="p-4 rounded-2xl bg-orange-50 dark:bg-orange-950/40 border border-orange-200 dark:border-orange-800 space-y-3">
            <h3 className="font-bold text-xs uppercase tracking-widest text-orange-800 dark:text-orange-200 flex items-center gap-2">
              <Activity size={16} />
              <span>{language === 'en' ? 'Fire Element & Thermal Diagnostics:' : 'Diagnostic de Chaleur & Élément Feu :'}</span>
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <div className="p-3 bg-white dark:bg-gray-800 rounded-xl border border-orange-100 dark:border-gray-700">
                <span className="text-gray-500 block">{language === 'en' ? 'Fire Ratio in Litany:' : 'Ratio de Lettres de Feu :'}</span>
                <span className="font-bold text-orange-600 dark:text-orange-400 text-sm">
                  {analysis.fireRatioPct}% ({analysis.fireCount} / {analysis.totalLetters})
                </span>
              </div>

              <div className="p-3 bg-white dark:bg-gray-800 rounded-xl border border-orange-100 dark:border-gray-700">
                <span className="text-gray-500 block">{language === 'en' ? 'Mental Fatigue Level:' : 'Niveau de Fatigue Mentale :'}</span>
                <span className="font-bold text-sm" style={{ color: analysis.riskColor }}>
                  {language === 'en' ? analysis.riskLevelEn : language === 'ha' ? analysis.riskLevelHa : analysis.riskLevelFr}
                </span>
              </div>
            </div>
          </div>

          {/* Cooling Counter-Balance Card */}
          <div className="p-4 rounded-2xl bg-gray-50 dark:bg-gray-800/80 border border-gray-200 dark:border-gray-700 space-y-3 text-xs">
            <h4 className="font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
              <HeartHandshake size={16} className="text-teal-500" />
              <span>{language === 'en' ? 'Cooling Spiritual Counter-Balance:' : 'Protocole de Refroidissement & Apaisement :'}</span>
            </h4>

            <div className="space-y-2">
              <div className="p-2.5 bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-700">
                <span className="text-gray-500 block">{language === 'en' ? 'Cooling Water/Earth Dhikr:' : 'Dhikr Rafraîchissant (Eau / Paix) :'}</span>
                <span className="font-bold text-emerald-600 dark:text-emerald-400">
                  {language === 'en' ? analysis.coolingDhikrEn : language === 'ha' ? analysis.coolingDhikrHa : analysis.coolingDhikrFr}
                </span>
              </div>

              <div className="p-2.5 bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-700">
                <span className="text-gray-500 block">{language === 'en' ? 'Cooling Incense & Ablution:' : 'Encens Apaisant & Ablutions :'}</span>
                <span className="font-bold text-indigo-600 dark:text-indigo-400">
                  {language === 'en' ? analysis.coolingFumigationEn : language === 'ha' ? analysis.coolingFumigationHa : analysis.coolingFumigationFr}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
